name: Redocly API Docs Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  REDOCLY_VERSION: 1.x
  DOC_OUTPUT_DIR: dist

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      # 检出代码
      - name: Checkout repository
        uses: actions/checkout@v4

      # 安装 yq YAML 处理工具
      - name: Install yq
        run: |          
          sudo wget https://github.com/mikefarah/yq/releases/download/v4.44.3/yq_linux_amd64 -O /usr/local/bin/yq
          sudo chmod +x /usr/local/bin/yq

      # 提取 OpenAPI 版本号
      - name: Extract API Version
        id: version
        run: |          
          VERSION=$(yq e '.info.version' openapi.yaml | sed 's/^v//')
          echo "API_VERSION=$VERSION" >> $GITHUB_ENV

      # 设置 Node.js 环境
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/Jod
          cache: npm

      # 安装 Redocly CLI
      - name: Install Redocly CLI
        run: |          
          npm install -g @redocly/cli@${REDOCLY_VERSION}

      # 构建 API 文档
      - name: Build docs with Redocly
        run: |          
          redocly build-docs openapi.yaml \
            --version ${{ env.API_VERSION }} \
            --output ${DOC_OUTPUT_DIR}/index.html \
            --title "CertVault API Documentation" \
            --theme default \
            --no-server

      # 部署到 GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./${DOC_OUTPUT_DIR}
          commit_message: ${{ github.event.head_commit.message || "Update API docs" }}
          enable_jekyll: false
      
      - name: Cache Redocly
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          keep_files: true